name: ci

on:
  # 手动触发事件
  workflow_dispatch:
    inputs:
      enable:
        description: "启用或禁用自动 GitHub 自动全绿功能"
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
  push:
    branches:
      - master
  schedule:
    # 每 15 分钟尝试触发一次，一天有 96 个 15 分钟的时间段
    - cron: "*/15 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    # 检查是否满足触发条件
    if: |
      (github.event_name == 'schedule' &&
        (
          "`expr ${{ github.run_number }} % 4`" == "0" ||
          "`expr ${{ github.run_number }} % 3`" == "0" ||
          "`expr ${{ github.run_number }} % 2`" == "0"
        )
      ) ||
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.enable == 'true')
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          set -e
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.NAME }}
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          # 定义 2024 年指定日期列表
          dates=("2024-03-31" "2024-04-03" "2024-04-04" "2024-04-05" "2024-04-06" "2024-04-07" "2024-04-10" "2024-04-13" "2024-04-14" "2024-04-17" "2024-04-20" "2024-04-21")
          start_date="2024-01-01"  
          end_date="2024-12-31"
          current_date=$start_date
          while [ "$(date -d "$current_date" +%s)" -le "$(date -d "$end_date" +%s)" ]; do
            if printf '%s\n' "${dates[@]}" | grep -qx "$current_date"; then
              for ((i = 0; i < 100; i++)); do
                random_time=$(printf "%02d:%02d:%02d" $((RANDOM % 24)) $((RANDOM % 60)) $((RANDOM % 60)))
                datetime="$current_date $random_time"
                export GIT_COMMITTER_DATE="$datetime"
                export GIT_AUTHOR_DATE="$datetime"
                commit_message="Keep writing documents at $datetime (Commit $((i + 1)))"
                git commit --allow-empty -m "$commit_message"
              done
            fi
            current_date=$(date -d "$current_date + 1 day" +%Y-%m-%d)
          done
          git push    
